spring:
  application:
    name: hello-spring

server:
  port: 8866

config:
  jdbc:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true
    username: root
    password: test123456
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 20
      # 最大连接池数量
      maxActive: 200
      # 最小连接池数量
      minIdle: 5